// NOTE: This file is auto-generated by React Cosmos.
// It imports all fixture and decorator modules, making them available to the
// React Cosmos renderer along with the renderer config.

import type { RendererConfig, UserModuleWrappers } from 'react-cosmos-core';

import * as fixture0 from './example/fixtures/Button.fixture';

export const rendererConfig: RendererConfig = {
  "webSocketUrl": "ws://192.168.56.1:5000",
  "rendererUrl": "http://localhost:3008/cosmos.html"
};

const fixtures = {
  'example/fixtures/Button.fixture.tsx': { module: fixture0 }
};

const decorators = {};

export const moduleWrappers: UserModuleWrappers = {
  lazy: false,
  fixtures,
  decorators
};
