import { mountDomRenderer } from 'react-cosmos-dom';
// @ts-ignore
import * as mountArgs from '../cosmos.imports'; // This file is auto-generated by Cosmos

// You might need to import CSS files here if you are using tailwind for example
// Because the bundler needs to know about them
// Note: cosmos.config.json's globalImports not going to work with Tailwind (for example) as it expects static CSS files.
//import "../src/index.css"

mountDomRenderer(mountArgs);